library/home/urls.py
from . import views
from django.urls import path,include

urlpatterns = [
    path('', views.main,name="main"),
    path('addstudent', views.addstudent,name="addstudent"),
    path('addbook', views.addbook,name="addbook"),
    path('borrowbook/<int:myid>', views.borrowbook,name="borrowbook"),
    path('studentinfo', views.studentinfo,name="studentinfo"),
    path('updatebook/<int:myid>', views.updatebook,name="updatebook"),
    path('deletebook', views.deletebook,name="deletebook"),
    path('info/<int:myid>', views.info,name="info"),
    path('delstudent/<int:myid>', views.delstudent,name="delstudent"),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

library/home/models.py
from django.db import models
class Student(models.Model):
    name = models.CharField(max_length=30)
    enroll=models.CharField(max_length=20)
    branch = models.CharField(max_length=10)
    sem=models.IntegerField()
    year = models.CharField(max_length=30)
    mob=models.CharField(max_length=11)
    def __str__(self):
        return self.name+" "+self.branch+" "+self.year
    
class Library(models.Model):
    book=models.CharField(max_length=30)
    category=models.CharField(max_length=30)
    language=models.CharField(max_length=10)
    description=models.TextField()
    publisher=models.CharField(max_length=30)
    paperback=models.CharField(max_length=10)
    sid=models.ForeignKey(Student,on_delete=models.CASCADE,blank=True,null=True)
    def __str__(self):
        return self.book
    

library/home/forms.py
from django.forms import ModelForm, fields
from .models import Library, Student
class AddBookForm(ModelForm):
    class Meta:
        model=Library
        fields=['book','category','language','description','publisher','paperback','sid']

library/home/views.py
import re
from django.shortcuts import render,redirect,get_object_or_404
from .models import Student,Library
from django.contrib import messages
from .forms import AddBookForm

def main(request):
    a=Library.objects.all()
    return render(request,'main.html',{'lib':a})

def addstudent(request):
    if request.method == 'POST':
        s=Student()
        s.name=request.POST['name']
        s.enroll=request.POST['enroll']
        s.branch=request.POST['branch']
        s.sem=request.POST['sem']
        s.year=request.POST['year']
        s.mob=request.POST['mob']
        s.save()
        messages.success(request,"Student Added Successfully")
        return redirect('/')
    else:
        return render(request,'addstudent.html')
    
def addbook(request):
    if request.method == 'POST':
        l=Library()
        l.book=request.POST['book']
        l.category=request.POST['category']
        l.language=request.POST['language']
        l.description=request.POST['description']
        l.publisher=request.POST['publisher']
        l.paperback=request.POST['paperback']
        l.save()
        messages.success(request,"Book Added Successfully")
        return redirect('/')
    else:
        return render(request,'addbook.html')

def borrowbook(request,myid):
    obj = get_object_or_404(Library, id=myid)
    form = AddBookForm(request.POST or None ,request.FILES or None ,instance=obj)
    print(form)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.save()
        messages.success(request, "You successfully Borrowed the Book")
        return redirect('/')
    else:
        # messages.success(request, "Something went wrong please try again")
        return render(request,'borrowbook.html' , {'info':form})
    
def studentinfo(request):
    s=Student.objects.all()
    return render(request,'student.html',{'st':s})

def updatebook(request,myid):
    obj = get_object_or_404(Library, id=myid)
    form = AddBookForm(request.POST or None ,request.FILES or None ,instance=obj)
    print(form)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.save()
        messages.success(request, "You successfully Updated the Book")
        return redirect('/')
    else:
        # messages.success(request, "Something went wrong please try again")
        return render(request,'updatebook.html' , {'info':form})
    
def deletebook(request,myid):
    id=int(myid)
    l=Library()
    l.id=id
    l.delete()
    messages.success(request,"Deleted Book Successfully!")
    return redirect("/") 

def delstudent(request,myid):
    myid=int(myid)
    t=Student()
    b=Library.objects.filter(sid_id=myid)
    for i in b:
        i.sid_id=None
        i.save()
    t.id=myid
    t.delete()
    messages.success(request,"You successfully deleted the Student")
    return redirect("/")
    

def info(request,myid):
    l=Library.objects.filter(id=myid).get()
    return render(request,'info.html',{'lib':l})

library/templates/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Library</title>
</head>
<style>
    body{
        background-color: whitesmoke;
    }
</style>
<body>
    <div class="container my-3">
        <h1 class="display-4">Add Your Favorite Book</h1>
    {% load crispy_forms_tags %}
    <form action="" method="POST">
        {%csrf_token %}
        <div class="mb-3">
            <label for="formGroupExampleInput" class="form-label">Book Name</label>
            <input type="text" name="book" class="form-control" id="formGroupExampleInput" placeholder="Book Name">
          </div>
          <div class="mb-3">
            <label for="formGroupExampleInput2" class="form-label">Category</label>
            <input type="text" name="category" class="form-control" id="formGroupExampleInput2" placeholder="Category">
          </div>
          <div class="mb-3">
            <label for="formGroupExampleInput2" class="form-label">Language</label>
            <input type="text" name="language" class="form-control" id="formGroupExampleInput2" placeholder="Language">
          </div>
          <div class="mb-3">
            <label for="formGroupExampleInput2" class="form-label">Description</label>
            <input type="text" name="description" class="form-control" id="formGroupExampleInput2" placeholder="Description">
          </div>
          <div class="mb-3">
            <label for="formGroupExampleInput2" class="form-label">Publisher</label>
            <input type="text" name="publisher" class="form-control" id="formGroupExampleInput2" placeholder="Publisher">
          </div>
          <div class="mb-3">
            <label for="formGroupExampleInput2" class="form-label">Paperback</label>
            <input type="text" name="paperback" class="form-control" id="formGroupExampleInput2" placeholder="Paperback">
          </div>
          <button class="btn btn-success" type="submit">Add Book</button>
    </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
crossorigin="anonymous"></script>
</body>
</html>

library/templates/addstudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container my-3">
        <h1 class="display-4">Add Student</h1>
    {% load crispy_forms_tags %}
    <form action="" method="POST">
        {%csrf_token %}
        <div class="mb-3">
            <label for="formGroupExampleInput" class="form-label">Student Name</label>
            <input type="text" name="name" class="form-control" id="formGroupExampleInput" placeholder="Enter Name">
          </div>
          <div class="mb-3">
            <label for="formGroupExampleInput2" class="form-label">Enrollment No</label>
            <input type="text" name="enroll" class="form-control" id="formGroupExampleInput2" placeholder="Enter Enrollment No">
          </div>
          <div class="mb-3">
            <label for="formGroupExampleInput2" class="form-label">Branch</label>
            <input type="text" name="branch" class="form-control" id="formGroupExampleInput2" placeholder="Enter Branch">
          </div>
          <div class="mb-3">
            <label for="formGroupExampleInput2" class="form-label">Semester</label>
            <input type="number" name="sem" class="form-control" id="formGroupExampleInput2" placeholder="Enter Semester">
          </div>
          <div class="mb-3">
            <label for="formGroupExampleInput2" class="form-label">Year</label>
            <input type="text" name="year" class="form-control" id="formGroupExampleInput2" placeholder="Enter Year">
          </div>
          <div class="mb-3">
            <label for="formGroupExampleInput2" class="form-label">Mobile No</label>
            <input type="text" name="mob" class="form-control" id="formGroupExampleInput2" placeholder="Enter Mobile No">
          </div>
          <button class="btn btn-success" type="submit">Add Student</button>
    </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
crossorigin="anonymous"></script>
</body>
</html>

library/templates/borrowbook.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="icon"
        href="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/facebook/304/open-book_1f4d6.png"
        type="image/gif" sizes="18x18">
    <title>Library</title>
    <style>
        .asteriskField {
            display: none;
        }
        
        .hidden{
            display: none;
        }
    </style>
</head>

<body>

    {% load crispy_forms_tags %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">PresenceKnowledge Library</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    {%if messages %}
    {%for message in messages%}
    {%if message.tags %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {%endif%}
    {%endfor%}
    {%endif%}
    <div class="container my-3">
        <h1 class="display-4">Borrow Book</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3 hidden">
                <label for="exampleInputEmail1" class="form-label">Upload Team Logo</label>
                {{info.book|as_crispy_field}}
            </div>
            <div class="mb-3 hidden">
                <label for="exampleInputEmail1" class="form-label">Upload Team Logo</label>
                {{info.category|as_crispy_field}}
            </div>
            <div class="mb-3 hidden">
                <label for="exampleInputEmail1" class="form-label">Upload Team Logo</label>
                {{info.language|as_crispy_field}}
            </div>
            <div class="mb-3 hidden">
                <label for="exampleInputEmail1" class="form-label">Upload Team Logo</label>
                {{info.description|as_crispy_field}}
            </div>
            <div class="mb-3 hidden">
                <label for="exampleInputEmail1" class="form-label">Upload Team Logo</label>
                {{info.publisher|as_crispy_field}}
            </div>
            <div class="mb-3 hidden">
                <label for="exampleInputEmail1" class="form-label">Upload Team Logo</label>
                {{info.paperback|as_crispy_field}}
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Select student</label>
                {{info.sid|as_crispy_field}}
            </div>
            <button type="submit" class="btn btn-primary">Borrow Book</button>
        </form>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous">
    </script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
</body>

</html>

library/templates/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Library</title>
</head>
<body style="background-color: azure;">
    <div class="container  my-3 ">
        <h1 style="color: rgb(93, 85, 104)" class="display-4">Book Details</h1>
        <hr>
        <div class= "cd-md-7">
            <h2 style="color: rgb(38, 98, 116)">{{lib.book}}</h2>
        </div>
        <div class= "cd-md-1">
            <h5 style="color: rgb(80, 218, 228)">Author : {{lib.publisher}}</h5>  
        </div>
        <div class= "cd-md-4" >
            {{lib.description}}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</body>
</html>

library/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'my.css' %}">
    <title>Library</title>
</head>
<body>
  <!-- <img src="{% static 'library.jpg' %}"> -->
    {%if messages %}
    {%for message in messages %}
    {%if message.tags%}
    <script>
    alert("{{message}}");
    </script>
    {%endif%}
    {%endfor%}
    {%endif%}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">PresenceKnowledge Library</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            </li>
          </ul>
          <div class="d-flex">
          <a class="btn btn-outline-success me-2" href="addstudent">Add Student</a><br/>
        <a class="btn btn-outline-success me-2" href="addbook">Add Book</a><br/>
      </div>
        </div>
      </div>
    </nav><br/>
    <div class="container">
      <h1 class="display-4">All Books</h1>
    <table class="table table-bordered">
      <thead class="table-dark">
      <tr>
        <th>Books</th>
        <th>Category</th>
        <th>Student who issued the book</th>
        <th>What do you want</th>
        <th>Update the Book</th>
        <th>More Info</th>
        </tr>
      </thead>
      <tbody>
        {% for i in lib %}
        <tr>
            <td>{{i.book}}</td>
            <td>{{i.category}}</td>
            <td>{{i.sid.name}}</td>
            <td>
              {% if i.sid is none %}
                            <a href="/borrowbook/{{i.id}}" class="btn btn-outline-primary">Borrow Book</a><br>
                            {% else %}
                            <a href="/borrowbook/{{i.id}}" class="btn btn-outline-danger">Reissue/change</a><br>
                            {% endif %}
            </td>
            <td>
               <a class="btn btn-outline-success" href="updatebook/{{i.id}}">Update</a>
          </td>
          <td>
            <a class="btn btn-outline-info" href="info/{{i.id}}">More Info</a>
       </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="d-grid gap-2">
       <a href ="studentinfo"class="btn btn-primary" type="button">Show Student Info</a>
    </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</body>
</html>

library/templates/student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <h1 class="display-4">All Students Info</h1>
      <table class="table table-bordered">
        <thead class="table-dark">
        <tr>
          <th>Student's Name</th>
          <th>Enrollment No</th>
          <th>Branch</th>
          <th>Semester</th>
          <th>Year</th>
          <th>Mobile No</th>
          <th>Remove the Student</th>
          </tr>
        </thead>
        <tbody>
            {% for i in st%}
            <tr>
                <td>{{i.name}}</td>
                <td>{{i.enroll}}</td>
                <td>{{i.branch}}</td>
                <td>{{i.sem}}</td>
                <td>{{i.year}}</td>
                <td>{{i.mob}}</td>
                <td><a class="btn btn-outline-danger" href="delstudent/{{i.id}}">Remove</a></td>
            </tr>
            {% endfor %}
        </tbody>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</body>
</html>

library/templates/updatebook.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
        <style>
            #id_sid {
                display: none;
            }

            .asteriskField {
                display: none;
            }

        </style>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>

    <body>
        {% load crispy_forms_tags %}
        <div class="container my-3">
            <h1 class="display-4">Update Book</h1>
            <hr>
            <form action="" method="POST">
                {%csrf_token %}
                {{info|crispy}}
                <button class="btn btn-success" type="submit">Update Book</button>
            </form>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous">
        </script>
    </body>
</html>